clone_folder: c:\dev2\node-mapnik

environment:
  node_pre_gyp_accessKeyId:
    secure: T1Pel/pv9SVfiVvZW8TLZnvZX6M4HQTiR7LUZnF1tuY=
  node_pre_gyp_secretAccessKey:
    secure: 8f5eTxMHpuVGHon2wbqrZuq3wzQfEuXMCcOyafBLza0T2VIOoBjbjDbgRbyRIzsT
  matrix:
  - nodejs_version: 0.10
  - nodejs_version: 0.11.13

platform:
  - x86
  - x64

shallow_clone: true

install:
  # http://help.appveyor.com/discussions/problems/618-nodejs-10030-doesnt-work-on-appveyor-cant-find-npm#comment_34002825
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - node -e "console.log('node version ' + process.version + ' architecture ' + process.arch);"
  - node --version
  - npm --version
  #- SET PATH=c:\python27;%PATH%
  #- SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  #- SET PATH=%APPDATA%\npm;%PATH%
  # add local node-pre-gyp dir to path
  #- SET PATH=node_modules\.bin;%PATH%
  # upgrade node-gyp to ensure it knows about msvs 2013
  # install node-pre-gyp so we can figure out versioned directory before starting
  #- npm install node-gyp node-pre-gyp
  #- scripts\build_against_sdk_00-START-HERE.bat
  # install 2014 c++ runtime
  - ps: Start-FileDownload "https://mapnik.s3.amazonaws.com/dist/dev/VS-2014-runtime/vcredist_%platform%.exe"
  - .\vcredist_%platform%.exe /q /norestart
  - npm install
  - npm test || true
  #- node-pre-gyp package
  #- SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
  #- ECHO commit message %CM%
  #- if not "%CM%" == "%CM:[publish binary]=%" node-pre-gyp publish

build: off
test: off
deploy: off